name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest -q

  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run minimal check
        run: python -m py_compile app.py || true

  deploy:
    runs-on: ubuntu-latest
    needs: [test-backend, lint-frontend]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/loan-approval-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/loan-approval-backend:latest

      - name: Build & Push Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/loan-approval-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/loan-approval-frontend:latest

      - name: Trigger Render Deploy (Backend)
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

      - name: Trigger Render Deploy (Frontend)
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
